// JavaScript Document
	$(function () {
			$('#activate_tagator').click(function () {
				if ($('#inputTagator').data('tagator') === undefined) {
					$('#inputTagator').tagator({
						autocomplete: ['Project Manager Sap',
										'Project Manager Testing',
										'Project Member',
										'Project Officer',
										'Project Planning Engineer',
										'Project Quantity Surveyor',
										'Project Scientist',
										'Project Secretary',
										'Project Site Engineer',
										'Project Supervisor',
										'Project Trainee',
										'Project Trainee Engineer',
										'Project Trainer',
										'Projectionist',
										'Promo Editor',
										'Promo Producer',
										'Promoter',
										'Promotional Executive',
										'Proof Reader',
										'Proofer',
										'Property Consultant',
										'Proposal Engineer',
										'Proprietor',
										'Psychologist',
										'Public Prosecutor',
										'Public Relation Executive',
										'Public Relation Officer',
										'Public Relations Executive',
										'Public Relations Manager',
										'Public Relations Officer',
										'Purchase Assistance',
										'Purchase Assistant',
										'Purchase Coordinator',
										'Purchase Engineer',
										'Purchase Executive',
										'Purchase Head',
										'Purchase Incharge',
										'Purchase Manager',
										'Purchase Officer',
										'Purchase Supervisor',
										'Purchasing Manager',
										'Purchasing Officer',
										'Qualified Assistant',
										'Quality',
										'Quality Analyst',
										'Quality Assistant',
										'Quality Associate',
										'Quality Assurance',
										'Quality Assurance Analyst',
										'Quality Assurance Associate',
										'Quality Assurance Chemist',
										'Quality Assurance Consultant',
										'Quality Assurance Engineer',
										'Quality Assurance Executive',
										'Quality Assurance Head',
										'Quality Assurance Incharge',
										'Quality Assurance Inspector',
										'Quality Assurance Leader',
										'Quality Assurance Manager',
										'Quality Assurance Member',
										'Quality Assurance Officer',
										'Quality Assurance Professional',
										'Quality Assurance Software Engineer',
										'Quality Assurance Specialist',
										'Quality Assurance Supervisor',
										'Quality Assurance Team Leader',
										'Quality Assurance Team Member',
										'Quality Assurance Test Engineer',
										'Quality Assurance Test Leader',
										'Quality Assurance Tester',
										'Quality Assurance Testing Engineer',
										'Quality Assurance Trainee',
										'Quality Auditor',
										'Quality Checker',
										'Quality Coach',
										'Quality Consultant',
										'Quality Control Analyst',
										'Quality Control Assistant',
										'Quality Control Chemist',
										'Quality Control Engineer',
										'Quality Control Executive',
										'Quality Control Incharge',
										'Quality Control Inspector',
										'Quality Control Manager',
										'Quality Control Microbiologist',
										'Quality Control Officer',
										'Quality Control Supervisor',
										'Quality Controller',
										'Quality Engineer',
										'Quality Evaluator',
										'Quality Executive',
										'Quality Head',
										'Quality Incharge',
										'Quality Inspector',
										'Quality Leader',
										'Quality Manager',
										'Quality Officer',
										'Quality Specialist',
										'Quality Supervisor',
										'Quality Test Engineer',
										'Quality Tester',
										'Quantity Surveyor',
										'Radio Jockey',
										'Radio Operator',
										'Radiographer',
										'Radiologist',
										'Ramp Agent',
										'Ramp Supervisor',
										'Reader',
										'Real Estate Agent',
										'Reality Producer',
										'Receptionist',
										'Receptionist & Computer Oper',
										'Receptionist & Computer Operator',
										'Receptionist & Office Assistant',
										'Receptionist & Secretary',
										'Receptionist & Telephone Ope',
										'Receptionist & Telephone Operator',
										'Receptionist & Typist',
										'Recording Engineer',
										'Recordist',
										'Recovery Agent',
										'Recovery Officer',
										'Recruiter',
										'Recruitment Associate',
										'Recruitment Consultant',
										'Recruitment Coordinator',
										'Recruitment Executive',
										'Recruitment Manager',
										'Recruitment Officer',
										'Recruitment Specialist',
										'Regional Accountant',
										'Regional Business Manager',
										'Regional Credit Manager',
										'Regional Director',
										'Regional Head',
										'Regional Head South',
										'Regional Legal Manager',
										'Regional Manager',
										'Regional Manager East',
										'Regional Manager Marketing',
										'Regional Manager North',
										'Regional Manager Sales',
										'Regional Manager South',
										'Regional Manager West',
										'Regional Marketing Manager',
										'Regional Officer',
										'Regional Sales Executive',
										'Regional Sales Manager',
										'Regional Sales Manager North',
										'Regional Sales Officer',
										'Regional Security Manager',
										'Regional Security Officer',
										'Registered Nurse',
										'Registrar',
										'Regulating Petty Officer',
										'Regulatory Affairs Executive',
										'Regulatory Affairs Officer',
										'Regulatory Officer',
										'Relationship Associate',
										'Relationship Executive',
										'Relationship Manager',
										'Relationship Officer',
										'Report Analyst',
										'Report Developer',
										'Reporter',
										'Reporter & Anchor',
										'Reporter & Copy Editor',
										'Reporter & Editor',
										'Reporter & Photographer',
										'Reporter Sub Editor',
										'Reporter Trainee',
										'Reporter & Sub Editor',
										'Reporting Analyst',
										'Representative',
										'Research & Development Engineer',
										'Research Analyst',
										'Research Assistant',
										'Research Associate',
										'Research Chemist',
										'Research Development Chemist',
										'Research Development Design Engineer',
										'Research Development Embedded Engineer',
										'Research Development Engineer',
										'Research Development Executive',
										'Research Development Firmware Engineer',
										'Research Development Manager',
										'Research Development Officer',
										'Research Development Software Engineer',
										'Research Development Trainee',
										'Research Editor',
										'Research Engineer',
										'Research Executive',
										'Research Fellow',
										'Research Intern',
										'Research Manager',
										'Research Officer',
										'Research Scholar',
										'Research Scientist',
										'Research Trainee',
										'Researcher',
										'Reservation & Ticketing Agent',
										'Reservation & Ticketing Executive',
										'Reservation & Ticketing Officer',
										'Reservation & Ticketing Staff',
										'Reservation Agent',
										'Reservation Assistant',
										'Reservation Counter Staff',
										'Reservation Executive',
										'Reservation Incharge',
										'Reservation Manager',
										'Reservation Officer',
										'Reservation Staff',
										'Reservation Supervisor',
										'Reservation Ticketing Agent',
										'Reservation Trainee',
										'Reservations Executive',
										'Reservations Manager',
										'Residence Engineer',
										'Resident Architect',
										'Resident Construction Manager',
										'Resident Doctor',
										'Resident Editor',
										'Resident Engineer',
										'Resident Manager',
										'Resident Medical Officer',
										'Residential Engineer',
										'Residential Medical Officer',
										'Resolution Expert',
										'Resort Manager',
										'Resource Consultant',
										'Resource Executive',
										'Resource Manager',
										'Resourcing Executive',
										'Response Executive',
										'Rest Manager',
										'Restaurant Captain',
										'Restaurant General Manager',
										'Restaurant Hostess',
										'Restaurant Incharge',
										'Restaurant Manager',
										'Restaurant Supervisor',
										'Retail Executive',
										'Retail Manager',
										'Retail Merchandiser',
										'Retail Outlet Manager',
										'Retail Planner',
										'Retail Sales Executive',
										'Retail Sales Manager',
										'Retail Sales Officer',
										'Retail Store Manager',
										'Retailer',
										'Retainer',
										'Retainer Advocate',
										'Retention Executive',
										'Revenue Manager',
										'Rigger',
										'Rigging Artist',
										'Room Attendant',
										'Room Boy',
										'Room Service Order Maker',
										'Rooms Division Manager',
										'Roto Artist',
										'Route Trainer',
										'Rural Sales Promoter',
										'Safety & Security Officer',
										'Safety Engineer',
										'Safety Manager',
										'Safety Officer',
										'Safety Supervisor',
										'Sailor',
										'Sales & Application Engineer',
										'Sales & Marketing',
										'Sales & Marketing Engineer',
										'Sales & Marketing Executive',
										'Sales & Marketing Manager',
										'Sales & Service Engineer',
										'Sales & Service Executive',
										'Sales Accounts Manager',
										'Sales Advisor',
										'Sales Agent',
										'Sales Assistant',
										'Sales Associate',
										'Sales Consultant',
										'Sales Coordinator',
										'Sales Development Manager',
										'Sales Director',
										'Sales Engineer',
										'Sales Executive',
										'Sales Head',
										'Sales Incharge',
										'Sales Manager',
										'Sales Officer',
										'Sales Promoter',
										'Sales Promotion Executive',
										'Sales Promotion Manager',
										'Sales Representative',
										'Sales Representive',
										'Sales Staff',
										'Sales Supervisor',
										'Sales Team Leader',
										'Sales Team Manager',
										'Sales Territory Supervisor',
										'Sales Trainee',
										'Salesman',
										'Sample Coordinator',
										'Sampling Coordinator',
										'Sampling Head',
										'Sampling Incharge',
										'Sampling Manager',
										'Sampling Merchandiser',
										'Sanskrit Teacher',
										'Scanner Operator',
										'Scanning Operator',
										'Scheduling Executive',
										'School Assistant',
										'School Counsellor',
										'School Teacher',
										'Science Teacher',
										'Scientific Assistant',
										'Scientific Officer',
										'Scientific Officer D',
										'Scientific Sales Executive',
										'Scientist',
										'Screen Printer',
										'Scriptwriter',
										'Search Engine Optimizer',
										'Second Engineer',
										'Second In Command',
										'Secondary Grade Teacher',
										'Secondary School Teacher',
										'Secondary Teacher',
										'Secretarial Assistant',
										'Secretarial Executive',
										'Secretarial Officer',
										'Secretary',
										'Secretary & Computer Operator',
										'Secretary & Office Assistant',
										'Secretary & Receptionist',
										'Secretary & Stenographer',
										'Secretary To Chairman',
										'Secretary To Director',
										'Secretary To Executive Director',
										'Secretary To General Manager',
										'Secretary To Managing Director',
										'Secretary To President',
										'Secretary To Regional Manager',
										'Secretary To The Director',
										'Secretary To Vice President',
										'Section Commander',
										'Section Engineer',
										'Section Head',
										'Section Manager',
										'Section Officer',
										'Security & Administration Officer',
										'Security & Fire Officer',
										'Security & Safety Officer',
										'Security Administrator',
										'Security Advisor',
										'Security Agent',
										'Security Analyst',
										'Security Asset',
										'Security Assistant',
										'Security Consultant',
										'Security Controller',
										'Security Coordinator',
										'Security Engineer',
										'Security Examiner',
										'Security Executive',
										'Security Facilitator',
										'Security Guard',
										'Security Guards',
										'Security Head',
										'Security Incharge',
										'Security Inspector',
										'Security Manager',
										'Security Officer',
										'Security Personnel',
										'Security Specialist',
										'Security Sub Assistant',
										'Security Supervisor',
										'Security Team Leader',
										'Selection Grade Lecturer',
										'Senior D Animator',
										'Senior D Artist',
										'Senior Abap Consultant',
										'Senior Accountant',
										'Senior Accountants',
										'Senior Accounts',
										'Senior Accounts Assistant',
										'Senior Accounts Executive',
										'Senior Accounts Manager',
										'Senior Accounts Officer',
										'Senior Administration Executive',
										'Senior Administration Officer',
										'Senior Administrative Officer',
										'Senior Administrator',
										'Senior Advisor',
										'Senior Advocate',
										'Senior Agency Manager',
										'Senior Agent',
										'Senior Analyst',
										'Senior Analyst Programmer',
										'Senior Analytical Chemist',
										'Senior Animator',
										'Senior Application Consultant',
										'Senior Application Developer',
										'Senior Application Engineer',
										'Senior Application Programmer',
										'Senior Applications Developer',
										'Senior Applications Engineer',
										'Senior Architect',
										'Senior Architectural Assistant',
										'Senior Architectural Draughtsman',
										'Senior Area Manager',
										'Senior Area Sales Executive',
										'Senior Area Sales Manager',
										'Senior Art Director',
										'Senior Artist',
										'Senior Assistant',
										'Senior Assistant Accounts',
										'Senior Assistant Architect',
										'Senior Assistant Editor',
										'Senior Assistant Manager',
										'Senior Associate',
										'Senior Associate Advocate',
										'Senior Associate Architect',
										'Senior Associate Attorney',
										'Senior Associate Consultant',
										'Senior Associate Editor',
										'Senior Associate Human Resources',
										'Senior Associate Lawyer',
										'Senior Associate Quality Assurance',
										'Senior Associate Technology',
										'Senior Associates',
										'Senior Attorney',
										'Senior Audit Assistant',
										'Senior Audit Executive',
										'Senior Audit Manager',
										'Senior Audit Officer',
										'Senior Auditor',
										'Senior Autocad Draughtsman',
										'Senior Av Editor',
										'Senior Bartender',
										'Senior Billing Engineer',
										'Senior Branch Manager',
										'Senior Brand Manager',
										'Senior Brew Master',
										'Senior Business Analyst',
										'Senior Business Associate',
										'Senior Business Consultant',
										'Senior Business Correspondent',
										'Senior Business Development Executive',
										'Senior Business Development Manager',
										'Senior Business Executive',
										'Senior Business Manager',
										'Senior Buyer',
										'Senior Cabin Crew',
										'Senior Cad Designer',
										'Senior Cad Draughtsman',
										'Senior Cad Engineer',
										'Senior Cad Operator',
										'Senior Cameraman',
										'Senior Captain',
										'Senior Cashier',
										'Senior Cco',
										'Senior Ccs',
										'Senior Cdp',
										'Senior Chef De Partie',
										'Senior Chemist',
										'Senior Civil Engineer',
										'Senior Clerk',
										'Senior Client Servicing Executive',
										'Senior Clinical Research Associate',
										'Senior Co Ordinator',
										'Senior Commandant',
										'Senior Commercial Executive',
										'Senior Commercial Officer',
										'Senior Commisioned Officer',
										'Senior Commission Officer',
										'Senior Commissioned Office',
										'Senior Commissioned Officer',
										'Senior Compositor',
										'Senior Computer Operator',
										'Senior Computer Teacher',
										'Senior Construction Engineer',
										'Senior Construction Manager',
										'Senior Consultant',
										'Senior Content Analyst',
										'Senior Content Developer',
										
										'Senior Content Editor',
										'Senior Content Executive',
										'Senior Content Writer',
										'Senior Cook',
										'Senior Copy Editor',
										'Senior Copywriter',
										'Senior Correspondent',
										'Senior Counsel',
										'Senior Counsellor',
										'Senior Counter Executive']
					});
					
				$('#activate_tagator').val('destroy tagator');
				} else {
					$('#inputTagator').tagator('destroy');
					$('#activate_tagator').val('activate tagator');
				}
			});
			$('#activate_tagator').trigger('click');
			
			/////company_type//////
			
			$('#company_type').click(function () {
				if ($('#inputcompanyType').data('tagator') === undefined) {
			$('#inputcompanyType').tagator({
						autocomplete: ['Public Company',
										'Society',
										'Trust',
										'Privately Held',
										'Partnership',
										'Government Agency',
										'Non Profit',]
					});
				$('#company_type').val('destroy tagator');
				} else {
					$('#inputcompanyType').tagator('destroy');
					$('#company_type').val('Company Type');
				}
			});
			$('#company_type').trigger('click');
			
			/////company_size//////
			
			$('#company_size').click(function () {
				if ($('#inputcompanySize').data('tagator') === undefined) {
			$('#inputcompanySize').tagator({
						autocomplete: ['1-10',
										'11-50',
										'50-100',
										'101-200',
										'201-500',
										'501-1000',
										'1001-5000',
										'5000+',]
					});
				$('#company_size').val('destroy tagator');
				} else {
					$('#inputcompanySize').tagator('destroy');
					$('#company_size').val('Company Size');
				}
			});
			$('#company_size').trigger('click');
			
		});